[2024-08-24T18:36:59.768+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T18:36:59.788+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employee.get_data manual__2024-08-24T18:36:56.685766+00:00 [queued]>
[2024-08-24T18:36:59.798+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employee.get_data manual__2024-08-24T18:36:56.685766+00:00 [queued]>
[2024-08-24T18:36:59.799+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T18:36:59.815+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2024-08-24 18:36:56.685766+00:00
[2024-08-24T18:36:59.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T18:36:59.824+0000] {standard_task_runner.py:72} INFO - Started process 821 to run task
[2024-08-24T18:36:59.824+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'process_employee', 'get_data', 'manual__2024-08-24T18:36:56.685766+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/employee_DAG.py', '--cfg-path', '/tmp/tmp3t9r6ax4']
[2024-08-24T18:36:59.825+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask get_data
[2024-08-24T18:36:59.876+0000] {task_command.py:467} INFO - Running <TaskInstance: process_employee.get_data manual__2024-08-24T18:36:56.685766+00:00 [running]> on host 67412decceee
[2024-08-24T18:36:59.965+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employee' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T18:36:56.685766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T18:36:56.685766+00:00'
[2024-08-24T18:36:59.966+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T18:37:00.242+0000] {base.py:84} INFO - Retrieving connection 'employee_db_conn'
[2024-08-24T18:37:00.354+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-24T18:37:00.369+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T18:37:00.370+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=process_employee, task_id=get_data, run_id=manual__2024-08-24T18:36:56.685766+00:00, execution_date=20240824T183656, start_date=20240824T183659, end_date=20240824T183700
[2024-08-24T18:37:00.401+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-24T18:37:00.429+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-24T18:37:00.432+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
