[2024-08-24T18:37:01.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-24T18:37:01.187+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employee.merge_data manual__2024-08-24T18:36:56.685766+00:00 [queued]>
[2024-08-24T18:37:01.198+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employee.merge_data manual__2024-08-24T18:36:56.685766+00:00 [queued]>
[2024-08-24T18:37:01.198+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-24T18:37:01.214+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2024-08-24 18:36:56.685766+00:00
[2024-08-24T18:37:01.221+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=823) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-24T18:37:01.223+0000] {standard_task_runner.py:72} INFO - Started process 824 to run task
[2024-08-24T18:37:01.223+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'process_employee', 'merge_data', 'manual__2024-08-24T18:36:56.685766+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/employee_DAG.py', '--cfg-path', '/tmp/tmpc7mdu0bu']
[2024-08-24T18:37:01.224+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask merge_data
[2024-08-24T18:37:01.276+0000] {task_command.py:467} INFO - Running <TaskInstance: process_employee.merge_data manual__2024-08-24T18:36:56.685766+00:00 [running]> on host 67412decceee
[2024-08-24T18:37:01.362+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employee' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-24T18:36:56.685766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-24T18:36:56.685766+00:00'
[2024-08-24T18:37:01.363+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-24T18:37:01.376+0000] {base.py:84} INFO - Retrieving connection 'employee_db_conn'
[2024-08-24T18:37:01.475+0000] {python.py:240} INFO - Done. Returned value was: 1
[2024-08-24T18:37:01.501+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-24T18:37:01.502+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=process_employee, task_id=merge_data, run_id=manual__2024-08-24T18:36:56.685766+00:00, execution_date=20240824T183656, start_date=20240824T183701, end_date=20240824T183701
[2024-08-24T18:37:01.559+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-24T18:37:01.576+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-24T18:37:01.578+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
